name: Install and update IWC tools

on:
  workflow_dispatch:
    inputs:
      instance:
        description: 'Galaxy Instance URL'
        required: true
        type: choice
        options:
        - galaxy-qa1.galaxy.cloud.e-infra.cz
        - usegalaxy.cz
        - galaxy-umsa.grid.cesnet.cz
jobs:
  update-repos:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Clone IWC repo
        run: git clone https://github.com/galaxyproject/iwc /tmp/iwc
      - name: Run update script
        run: python scripts/get_iwc_tools.py -w /tmp/iwc -s ${{ inputs.instance }} -u uncategorized.yml
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
            branch: iwc-update-${{ inputs.instance }}
            committer: CESNETbot <martin.cech@cesnet.cz>
            title: Install IWC tools for ${{ inputs.instance }}
            commit-message: "output of get_iwc_tools.py"
            labels: automated
            assignees: martenson
            reviewers: martenson
